# Generated by Django 4.0.3 on 2022-03-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='synopsis',
            field=models.CharField(max_length=250),
        ),
    ]
