# Generated by Django 4.0.3 on 2022-03-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookList', '0002_alter_bookmodel_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BookList.genremodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BookList.writermodel'),
            preserve_default=False,
        ),
    ]
