# Generated by Django 4.0.3 on 2022-03-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookList', '0003_alter_bookmodel_genre_alter_bookmodel_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='genre',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='genres',
            field=models.ManyToManyField(blank=True, to='BookList.genremodel'),
        ),
    ]
