# Generated by Django 4.0.3 on 2022-03-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookList', '0005_alter_bookmodel_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='genres',
            field=models.ManyToManyField(blank=True, to='BookList.genremodel'),
        ),
    ]
